Leaderboard - API Implementation
ReshyResh/Leaderboard-API-Js pull request #2
Opened 2021-08-30 21:47 UTC by ReshyResh

# New features: 
  - Function to make POST request to game API with user input.
  - Function to populate the list fetching data from the API.

# Live demo
### You can view the website by clicking [here](https://reshyresh.github.io/Leaderboard-API-Js/)

2021-08-30 22:08 UTC, rloterh requested changes
Hi Robert, 

You did extremely great on this project!👏 👏 
There are however a few issues that you still need to work on to go to the next project but you are almost there!👍 

## Good Points 👍  
- Sending and retrieving data is working as expected
- Nice UI design
- No linter errors


## Required Changes ♻️
- [ ] _Kindly check the comments under the review._

<br>
Cheers and Happy coding!👏 💻 🍷

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have 2 more limited reviews per this project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-08-30 22:08 UTC, rloterh commented on src/sendData.js
> +export default (name, score) => {
- [ ] The `promise` feature is not well implemented you _sending_ and _receiving_ methods. Kindly ensure to use `async` and `await` with the fetch method to send and receive data, so as to handle the data efficiently

2021-08-31 09:28 UTC, rloterh commented on src/sendData.js
> +export default (name, score) => {
This issue is not properly resolved

2021-08-31 09:31 UTC, rloterh requested changes
Hi Paka and Yannick-Noel, 

You did great on this project, and for making the changes requested in the previous review!👏 👏 
There are however a few issues that you still need to work on to go to the next project but you are almost there! 🚦 🚥 🚦 

## Good Points 👍  
- No linter errors

## Required Changes ♻️
- [ ] _Kindly check the comments above, made under the reviews of the previous code reviewer(s) and stating **not properly resolved**. Kindly take your time to correctly review those issues outlined by the previous code reviewers, and please check to see that the changes are working as intended._
<br>
Cheers and Happy coding!👏 💻 🍷

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have 1 more limited review per this project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-08-31 11:07 UTC, SpaYco reviewed
Hello 👋,

This is an additional review as a result of the second opinion request.

The review was valid, however, the CR wasn't informative enough, I'll make sure to pass a note to reduce these cases :)

But it looks like you solved the issue, please ask for another review in your Dashboard and the next Code Reviewer will mark it as approve right away :)

Keep rocking 🚀!

2021-08-31 12:45 UTC, vichuge approved these changes
# Approved project! ✅ 🥳 🎈 🎉🎉🎉🎉🎉🎉🎉🎉 

Hi there, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![InbornCandidHornet-size_restricted](https://user-images.githubusercontent.com/20563252/121368858-ff93ee80-c900-11eb-9ee8-e43b2b0d3382.gif)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-08-31 12:56 UTC, merged

2021-09-01 00:53 UTC, rloterh commented
**Hello Robert!**

I've just realized I missed one very important point in my second review. I missed your changes in my cloned version.

I'm sorry I couldn't point that out to you during my review. Kindly note, this was not on purpose 😊 

Happy coding! 🍷 💻 

Cheers!